# Generated by Django 4.2.27 on 2026-02-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('niveaux', models.IntegerField(choices=[(1, 'Debutant'), (2, 'Intermediare'), (3, 'Expert')], default=1)),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence', to='competence.categorie')),
            ],
        ),
    ]
